<a href="https://colab.research.google.com/github/mona-gomaa/python_for_DS/blob/python_DS_A/linear_algebra_numpy_(2)_taskDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import numpy to use it
import numpy as np 

## Write a Numpy program to compute the multiplication of two given matrixes

In [ ]:
#create matrices
mat1=np.array([[1,2,3],
               [0,5,0]])

mat2=np.array([[1,0,3],
               [9,2,8]])
#operation
print(mat1 * mat2)


[[ 1  0  9]
 [ 0 10  0]]


## Write a NumPy program to compute the determinant of a given square array

In [ ]:
#create square array

arr = np.array([[1,2],
               [1,7]])
res=np.linalg.det(arr)
res


4.999999999999999

## Write a NumPy program to compute the cross product of two given vectors

In [ ]:
v_1=np.array([1,2,3])

v_2=np.array([1,0,3])

print(v_1 .dot(v_2))

10


## Write a NumPy program to compute the condition number of a given matrix

In [ ]:
#create matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

cond_num = np.linalg.cond(A)

print("The condition number of the matrix A is:", cond_num)


The condition number of the matrix A is: 3.813147060626918e+16


## Write a NumPy program to compute the inverse of a given matrix

In [ ]:

mat=np.array([
    [1,2],
    [2,2]
    
])

In [ ]:
res=np.linalg.inv(mat)
res

array([[-1. ,  1. ],
       [ 1. , -0.5]])